### ISSUE TITLE
A way to prevent the rich header from being created

### ISSUE THREAD

**Issue by EchterAgo** [lordmulder/rich-header-eraser#2]
This is not actually an issue, so feel free to close it, I just wanted to put this here for reference. There is an undocumented switch to `link.exe` that disables the rich header: `/emittoolversioninfo:no`

I tested this with the 2019 build tools but I also found it is present in newer linker versions, up to 2022. Not sure about older versions.

**Comment by lordmulder** [comment]
Okay, thanks for info.
